org: rajivmehtaflex
app: gsqswithpython
service: aws-python-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hellodev:
    handler: handler.hello
    events:
      - snsSqs:
          name: TestEventDev
          topicArn: !Ref Topic

  helloprod:
    handler: handler.hello
    events:
      - snsSqs:
          name: TestEventProd 
          topicArn: !Ref Topic


resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: GajrajTopic
 
plugins:
  - "@agiledigital/serverless-sns-sqs-lambda"